version: '3'
volumes: 
  dados:

networks:
  banco:
  web:
  fila:

services: 
  db:
    image: postgres:9.6
    container_name: db
    volumes: 
      #Volume dos dados
      - dados:var/lib/postgresql/data
      #Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks: 
        - banco

  frontend:
    image: nginx:1.13 
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - web
    depends_on: 
      - app
      
  app:
    image: python:3.6
    container_name: pyt
    volumes: 
      #Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web 
      - fila
    depends_on:
      - db
      - queue

  worker:
      build: worker 
      container_name: work
      volumes:
        # Worker
        - ./worker:/worker 
      working_dir: /worker 
      command: worker.py
      networks:
        - fila 
      depends_on: 
        - queue
        - app

  queue:
    image: redis:3.2
    networks: 
      -fila